/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "AsymPDF.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(AsymPDF) 

 AsymPDF::AsymPDF(const char *name, const char *title, 
                        RooAbsReal& _phi_S,
                        RooAbsReal& _ phi_h,
                        RooAbsReal& _ a,
                        RooAbsReal& _ b) :
   RooAbsPdf(name,title), 
   phi_S("phi_S","phi_S",this,_phi_S),
    phi_h(" phi_h"," phi_h",this,_ phi_h),
    a(" a"," a",this,_ a),
    b(" b"," b",this,_ b)
 { 
 } 


 AsymPDF::AsymPDF(const AsymPDF& other, const char* name) :  
   RooAbsPdf(other,name), 
   phi_S("phi_S",this,other.phi_S),
    phi_h(" phi_h",this,other. phi_h),
    a(" a",this,other. a),
    b(" b",this,other. b)
 { 
 } 



 Double_t AsymPDF::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   Double_t asym = a + b*sin(3.0*phi_S + phi_h);
   return asym; 
 } 



